#!/bin/bash

#        _       _                _      
#       | |     | |              (_)     
#   __ _| |_ __ | |__   __ ___  ___ _ __ 
#  / _` | | '_ \| '_ \ / _` \ \/ / | '__| Shivaji Chalise (alphajr)
# | (_| | | |_) | | | | (_| |>  <| | |    http://www.github.com/shivajichalise
#  \__,_|_| .__/|_| |_|\__,_/_/\_\ |_|   
#         | |                   _/ |     
#         |_|                  |__/      
#
# Get now showing movies in Midtown Cinema, Pokhara, Nepal

mkdir -p "$HOME"/.cache/nowsh
cacheDir="$HOME/.cache/nowsh"
mkdir -p "$cacheDir"/movies

curl https://www.midtown.com.np/ -o "$cacheDir"/homePage
grep '<option value=".*>' "$cacheDir"/homePage | sed "s/.* value=\"\(.*\)\".*/\1/" > "$cacheDir"/movieIds
grep '<option value=".*>' "$cacheDir"/homePage | sed 's/^[ \t]*//;s/[ \t]*$//' | awk -v RS='<[^>]+>' -v ORS= '1' > "$cacheDir"/movieNames

file="$cacheDir"/movieIds

while read -r line;
do
  grep -A 31 "<div .* data-movie-id=\"${line}\">" "$cacheDir"/homePage | sed 's/^[ \t]*//;s/[ \t]*$//' | sed 's/.$//' | sed '/\S/!d' | awk '!a[$0]++' | sed 's/\-//' | sed '/^$/Q' > "$cacheDir"/movies/"$line".txt
  printf "\n"

  awk -v RS='<[^>]+>' -v ORS= '1' "$cacheDir"/movies/"$line".txt | sed '/\S/!d'
done < "$file"

rm -rf "$cacheDir"
